# Generated by Django 5.0.2 on 2024-02-12 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gerenciamento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enderecoentrega',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enderecoentrega',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gerenciamento.pedido'),
        ),
        migrations.AddField(
            model_name='pedidoproduto',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.pedido'),
        ),
        migrations.AddField(
            model_name='pedidoproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.produto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='produtos',
            field=models.ManyToManyField(through='gerenciamento.PedidoProduto', to='gerenciamento.produto'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='gerenciamento.produto'),
        ),
        migrations.AddField(
            model_name='produtoingrediente',
            name='ingrediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.ingrediente'),
        ),
        migrations.AddField(
            model_name='produtoingrediente',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.produto'),
        ),
        migrations.AddField(
            model_name='produto',
            name='ingredientes',
            field=models.ManyToManyField(through='gerenciamento.ProdutoIngrediente', to='gerenciamento.ingrediente'),
        ),
    ]
